Fix semantic error in THSTensor.cpp
While NULL is defined as 0 which is a valid default value for the float,
the default value should be 0.0f

This fixes the compiler warning:
TorchSharp/src/Native/LibTorchSharp/THSTensor.cpp(389,5): error G13A67890: converting to non-pointer type ‘float’ from NULL
[-Werror=conversion-null] [TorchSharp/src/Native/build.proj]
    389 |     CATCH_RETURN(float, NULL, (float)(tensor->data_ptr<c10::Half>())[i]);
        |     ^~~~~~~~~~~~